"""Snapshot branch heads and assemble a complete GitHub Pages site."""
import argparse
from html.parser import HTMLParser
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile


TOOLS_DIRECTORY = Path(__file__).resolve().parent
DEFAULT_CONFIG = TOOLS_DIRECTORY / "pages_branches.json"
SELECTOR_DIRECTORY = TOOLS_DIRECTORY / "pages"
SITE_MARKER = "Generated by tools/pages_site.py\n"
ROOT_FILES = {"index.html", "selector.css", "selector.js", "branches.json", ".nojekyll", ".pages-site"}
REQUIRED_BUILD_FILES = (
  "index.html", ".nojekyll", "interop.js", "game.css", "locales.json",
  "fonts/ChromaUI-SC.otf", "fonts/ChromaUI-JP.otf",
  "_framework/blazor.webassembly.js", "_framework/blazor.boot.json",
)


def validate_branch_name(name):
  if not isinstance(name, str) or not re.fullmatch(r"[A-Za-z0-9_][A-Za-z0-9_.-]*", name):
    raise ValueError(f"Unsafe branch name: {name!r}")
  if ".." in name or name.endswith((".", ".lock")) or name in ROOT_FILES:
    raise ValueError(f"Unsafe branch name: {name!r}")
  return name


def validate_repository(repository):
  if not isinstance(repository, str) or not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repository):
    raise ValueError("repository must be an owner/repository name")
  if any(part in {".", ".."} for part in repository.split("/")):
    raise ValueError("repository must be an owner/repository name")
  return repository


def load_branch_names(config=DEFAULT_CONFIG):
  names = json.loads(Path(config).read_text(encoding="utf-8"))
  if not isinstance(names, list) or not names:
    raise ValueError("Branch config must be a nonempty array")
  for name in names:
    validate_branch_name(name)
  if len(set(names)) != len(names):
    raise ValueError("Branch config contains duplicate names")
  return names


def validate_snapshot(snapshot):
  if not isinstance(snapshot, dict) or set(snapshot) != {"repository", "branches"}:
    raise ValueError("Snapshot must contain repository and branches")
  repository = validate_repository(snapshot["repository"])
  branches = snapshot["branches"]
  if not isinstance(branches, list) or not branches:
    raise ValueError("Snapshot branches must be a nonempty array")
  names = set()
  for branch in branches:
    if not isinstance(branch, dict) or set(branch) != {"name", "commit", "path"}:
      raise ValueError("Each snapshot branch must contain name, commit and path")
    name = validate_branch_name(branch["name"])
    if name in names:
      raise ValueError(f"Duplicate snapshot branch: {name}")
    names.add(name)
    if not isinstance(branch["commit"], str) or not re.fullmatch(r"[0-9a-f]{40}", branch["commit"]):
      raise ValueError(f"Invalid commit SHA for {name}")
    if branch["path"] != name + "/":
      raise ValueError(f"Invalid deployment path for {name}")
  return {"repository": repository, "branches": [dict(branch) for branch in branches]}


def read_snapshot(path):
  return validate_snapshot(json.loads(Path(path).read_text(encoding="utf-8")))


def remote_heads(names, require_all=True):
  refs = {f"refs/heads/{name}": name for name in names}
  result = subprocess.run(
    ["git", "ls-remote", "--heads", "origin", *refs],
    check=True, capture_output=True, text=True,
  )
  heads = {}
  for line in result.stdout.splitlines():
    fields = line.split()
    if len(fields) != 2 or fields[1] not in refs or not re.fullmatch(r"[0-9a-f]{40}", fields[0]):
      raise ValueError(f"Invalid remote head response: {line!r}")
    name = refs[fields[1]]
    if name in heads:
      raise ValueError(f"Duplicate remote head: {name}")
    heads[name] = fields[0]
  missing = [name for name in names if name not in heads]
  if missing and require_all:
    raise ValueError(f"Missing remote branches: {', '.join(missing)}")
  return heads


def repository_name():
  repository = os.environ.get("GITHUB_REPOSITORY")
  if repository is None:
    result = subprocess.run(
      ["git", "remote", "get-url", "origin"], check=True, capture_output=True, text=True,
    )
    match = re.fullmatch(r"(?:https://github\.com/|git@github\.com:)([^/]+/[^/]+?)(?:\.git)?/?", result.stdout.strip())
    if not match:
      raise ValueError("Set GITHUB_REPOSITORY when origin is not a GitHub repository")
    repository = match.group(1)
  return validate_repository(repository)


def create_snapshot(config=DEFAULT_CONFIG):
  names = load_branch_names(config)
  heads = remote_heads(names)
  return validate_snapshot({
    "repository": repository_name(),
    "branches": [{"name": name, "commit": heads[name], "path": name + "/"} for name in names],
  })


def is_current(snapshot):
  snapshot = validate_snapshot(snapshot)
  expected = {branch["name"]: branch["commit"] for branch in snapshot["branches"]}
  return remote_heads(list(expected), require_all=False) == expected


def branch_base_path(repository, name):
  owner, repository_name = validate_repository(repository).split("/")
  validate_branch_name(name)
  prefix = "" if repository_name.lower() == owner.lower() + ".github.io" else repository_name + "/"
  return "/" + prefix + name + "/"


class BaseParser(HTMLParser):
  def __init__(self):
    super().__init__()
    self.bases = []

  def handle_starttag(self, tag, attributes):
    if tag == "base":
      self.bases.append([value for name, value in attributes if name == "href"])


def validate_build(directory, base_path):
  if not directory.is_dir() or directory.is_symlink():
    raise ValueError(f"Missing build directory: {directory}")
  for path in directory.rglob("*"):
    if path.is_symlink():
      raise ValueError(f"Build contains a symbolic link: {path}")
  for name in REQUIRED_BUILD_FILES:
    if not (directory / name).is_file():
      raise ValueError(f"Missing build resource: {directory / name}")
  parser = BaseParser()
  parser.feed((directory / "index.html").read_text(encoding="utf-8"))
  if parser.bases != [[base_path]]:
    raise ValueError(f"Expected exactly one base href {base_path!r} in {directory / 'index.html'}")


def validate_output(output, inputs):
  if output.is_symlink():
    raise ValueError("Output cannot be a symbolic link")
  target = output.resolve()
  if target == target.parent:
    raise ValueError("Output cannot be a filesystem root")
  for source in inputs:
    source = source.resolve()
    if target == source or target in source.parents or source in target.parents:
      raise ValueError(f"Output overlaps an input: {source}")
  if not output.exists():
    return
  if not output.is_dir():
    raise ValueError("Output must be a directory")
  if not any(output.iterdir()):
    return
  marker = output / ".pages-site"
  if marker.is_symlink() or not marker.is_file() or marker.read_text(encoding="utf-8") != SITE_MARKER:
    raise ValueError("Refusing to replace an unrecognized nonempty output directory")
  manifest = output / "branches.json"
  if manifest.is_symlink():
    raise ValueError("Existing output manifest cannot be a symbolic link")
  previous = read_snapshot(manifest)
  branch_names = {branch["name"] for branch in previous["branches"]}
  for path in output.iterdir():
    if path.is_symlink() or path.name not in ROOT_FILES | branch_names:
      raise ValueError(f"Existing output contains an unrecognized entry: {path}")
    if path.name in branch_names and not path.is_dir():
      raise ValueError(f"Existing branch output is not a directory: {path}")
    if path.name in ROOT_FILES and not path.is_file():
      raise ValueError(f"Existing site resource is not a file: {path}")


def write_json(path, value):
  path.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def assemble(snapshot, artifacts, selector_script, output):
  snapshot = validate_snapshot(snapshot)
  artifacts, selector_script, output = map(Path, (artifacts, selector_script, output))
  sources = []
  for branch in snapshot["branches"]:
    source = artifacts / ("pages-web-" + branch["name"])
    validate_build(source, branch_base_path(snapshot["repository"], branch["name"]))
    sources.append((branch, source))
  selector_files = [SELECTOR_DIRECTORY / "index.html", SELECTOR_DIRECTORY / "selector.css", selector_script]
  for path in selector_files:
    if not path.is_file() or path.is_symlink():
      raise ValueError(f"Missing selector resource: {path}")
  validate_output(output, [artifacts, *selector_files])
  output.parent.mkdir(parents=True, exist_ok=True)
  with tempfile.TemporaryDirectory(prefix=f".{output.name}-", dir=output.parent) as temporary:
    temporary = Path(temporary)
    site = temporary / "site"
    site.mkdir()
    for branch, source in sources:
      destination = site / branch["name"]
      shutil.copytree(source, destination)
      write_json(destination / "build-info.json", {"name": branch["name"], "commit": branch["commit"]})
    for source, name in zip(selector_files, ["index.html", "selector.css", "selector.js"]):
      shutil.copy2(source, site / name)
    write_json(site / "branches.json", snapshot)
    (site / ".nojekyll").touch()
    (site / ".pages-site").write_text(SITE_MARKER, encoding="utf-8")
    backup = temporary / "previous"
    if output.exists():
      output.replace(backup)
    try:
      site.replace(output)
    except OSError:
      if backup.exists():
        backup.replace(output)
      raise


def main(argv=None):
  parser = argparse.ArgumentParser(description=__doc__)
  commands = parser.add_subparsers(dest="command", required=True)
  snapshot_parser = commands.add_parser("snapshot", help="Capture all configured remote branch heads")
  snapshot_parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
  snapshot_parser.add_argument("--output", type=Path, required=True)
  assemble_parser = commands.add_parser("assemble", help="Combine all branch artifacts and the selector")
  assemble_parser.add_argument("--snapshot", type=Path, required=True)
  assemble_parser.add_argument("--artifacts", type=Path, required=True)
  assemble_parser.add_argument("--selector-script", type=Path, required=True)
  assemble_parser.add_argument("--output", type=Path, required=True)
  current_parser = commands.add_parser("is-current", help="Print whether the snapshot still matches remote heads")
  current_parser.add_argument("--snapshot", type=Path, required=True)
  args = parser.parse_args(argv)
  try:
    if args.command == "snapshot":
      snapshot = create_snapshot(args.config)
      args.output.parent.mkdir(parents=True, exist_ok=True)
      write_json(args.output, snapshot)
    elif args.command == "assemble":
      assemble(read_snapshot(args.snapshot), args.artifacts, args.selector_script, args.output)
    else:
      print("true" if is_current(read_snapshot(args.snapshot)) else "false")
  except (OSError, ValueError, subprocess.CalledProcessError) as error:
    parser.exit(1, f"pages_site: {error}\n")


if __name__ == "__main__":
  main()
